POST http://localhost:3000/register
Content-Type: application/json

{

 "email": "rani29",
 "password": "rani25"

}
###
POST http://localhost:3000/registerumkm
Content-Type: application/json

{

 "email": "rani25",
 "password": "rani25"

}

###
GET http://localhost:3000/userdata
Content-Type: application/json

###
POST http://localhost:3000/loginuser
Content-Type: application/json

{
     "email": "rani25",
     "password": "rani25"
}

###
POST http://localhost:3000/loginadmin
Content-Type: application/json

{
    "email":"gantara@gmail.com",
    "password":"gantara"
}

###
POST http://localhost:3000/userdataupload
Content-Type: application/json

{
     "nama": "Rani",
     "email": "ranishb@gamil.com",
     "NoHp": "08227711",
     "TempatLahir": "Lintongnihuta",
     "TgglLahir": "2024-09-19",
     "Jenkel": "Perempuan"
}

###
GET http://localhost:3000/getdatauser
Content-Type: application/json

###
GET http://localhost:3000/getdataumkm
Content-Type: application/json

###
GET http://localhost:3000/getdataadmin
Content-Type: application/json
###
GET  http://localhost:3000/jumlahuser
Content-Type: application/json

###

###
GET  http://localhost:3000/jumlahumkm
Content-Type: application/json

###

# POST http://localhost:3000/upload
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="thumbnail"; filename="ikan.jpeg"
# Content-Type: image/jpeg

# images/ikan
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="nama"

# John Doe
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="email"

# johndoe@example.com
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="nohp"

# 1234567890
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="tempatusaha"

# Toko Baju
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="alamatusaha"

# Jl. Raya No. 123
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--


